targets:
  $default:
    builders:
      gql_build|ast_builder:
        enabled: true
      gql_build|req_builder:
        enabled: true
        options:
          schema: gql_example_cli|lib/schema.graphql
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: gql_example_cli|lib/schema.graphql
      gql_build|schema_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: gql_example_cli|lib/schema.graphql
      gql_build|var_builder:
        enabled: true
        options:
          schema: gql_example_cli|lib/schema.graphql
